import { PrismaClient } from '@prisma/client';
import { CarListingWithSeller, Seller } from '@/types';

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === 'development' ? ['query', 'error', 'warn'] : ['error'],
  });

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;

// ─── Mock data for fallback when database is not yet configured ─────────────

export const MOCK_SELLERS: Seller[] = [
  {
    id: 'seller-1',
    userId: 'user-1',
    shopName: 'Lakeside Motors',
    shopSlug: 'lakeside-motors',
    shopDescription: 'Quality used and imported cars in Blantyre. Trusted by hundreds of happy customers.',
    logo: 'https://images.unsplash.com/photo-1567789884554-0b844b597180?w=200',
    coverImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=1200',
    isVerified: true,
    plan: 'PRO',
    adCredits: 15,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'seller-2',
    userId: 'user-2',
    shopName: 'Capital Auto Sales',
    shopSlug: 'capital-auto-sales',
    shopDescription: 'Lilongwe\'s premier dealership. New, used, and certified pre-owned vehicles.',
    logo: 'https://images.unsplash.com/photo-1532581140115-3e355d1ed065?w=200',
    coverImage: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=1200',
    isVerified: true,
    plan: 'PREMIUM',
    adCredits: 50,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-10'),
  },
];

export const MOCK_CARS: CarListingWithSeller[] = [
  {
    id: 'car-1',
    sellerId: 'seller-1',
    title: '2018 Toyota Corolla',
    make: 'Toyota',
    model: 'Corolla',
    year: 2018,
    price: 8500000,
    currency: 'MWK',
    condition: 'USED',
    bodyType: 'SEDAN',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    mileage: 45000,
    color: 'Silver',
    engineSize: '1.8L',
    features: ['Air Conditioning', 'Power Steering', 'Airbags', 'ABS', 'Bluetooth', 'Reverse Camera'],
    description: 'Well-maintained Toyota Corolla, single owner, full service history. Perfect for daily commute in Lilongwe or Blantyre.',
    images: [
      'https://images.unsplash.com/photo-1549317661-bad32c169078?w=800',
      'https://images.unsplash.com/photo-1542362775-28fd2d1a10e2?w=800',
    ],
    status: 'ACTIVE',
    isFeatured: true,
    featuredUntil: new Date('2026-08-17'),
    views: 245,
    createdAt: new Date('2026-08-01'),
    updatedAt: new Date('2026-08-05'),
    seller: {
      id: 'seller-1',
      userId: 'user-1',
      shopName: 'Lakeside Motors',
      shopSlug: 'lakeside-motors',
      shopDescription: 'Quality used and imported cars in Blantyre.',
      logo: 'https://images.unsplash.com/photo-1567789884554-0b844b597180?w=200',
      coverImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=1200',
      isVerified: true,
      plan: 'PRO',
      adCredits: 15,
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-06-01'),
      user: {
        id: 'user-1',
        email: 'lakeside@example.com',
        password: '',
        name: 'Lakeside Motors',
        role: 'SELLER',
        phone: '+265 999 12 34 56',
        avatar: null,
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-06-01'),
      },
    },
  },
  {
    id: 'car-2',
    sellerId: 'seller-1',
    title: '2020 Honda Civic',
    make: 'Honda',
    model: 'Civic',
    year: 2020,
    price: 12500000,
    currency: 'MWK',
    condition: 'USED',
    bodyType: 'SEDAN',
    transmission: 'CVT',
    fuelType: 'PETROL',
    mileage: 28000,
    color: 'Blue',
    engineSize: '1.5L Turbo',
    features: ['Air Conditioning', 'Power Steering', 'Airbags', 'ABS', 'Sunroof', 'Leather Seats', 'Navigation'],
    description: 'Low mileage Honda Civic with turbo engine. Sporty and fuel-efficient. Import from Japan.',
    images: [
      'https://images.unsplash.com/photo-1606220945770-5bbb0c1a1fee?w=800',
      'https://images.unsplash.com/photo-1605559424843-9e4c0452df90?w=800',
    ],
    status: 'ACTIVE',
    isFeatured: true,
    featuredUntil: new Date('2026-08-17'),
    views: 312,
    createdAt: new Date('2026-08-02'),
    updatedAt: new Date('2026-08-03'),
    seller: MOCK_SELLERS[0] as any,
  },
  {
    id: 'car-3',
    sellerId: 'seller-2',
    title: '2019 Mazda CX-5',
    make: 'Mazda',
    model: 'CX-5',
    year: 2019,
    price: 15000000,
    currency: 'MWK',
    condition: 'USED',
    bodyType: 'SUV',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    mileage: 35000,
    color: 'Red',
    engineSize: '2.5L',
    features: ['Air Conditioning', 'Power Steering', 'Airbags', 'ABS', '4WD', 'Cruise Control', 'Bluetooth', 'Reverse Camera'],
    description: 'Mazda CX-5 SUV in excellent condition. Spacious and reliable for Malawi roads.',
    images: [
      'https://images.unsplash.com/photo-1605581809338-4f3f9d12c1ed?w=800',
    ],
    status: 'ACTIVE',
    isFeatured: false,
    featuredUntil: null,
    views: 189,
    createdAt: new Date('2026-08-03'),
    updatedAt: new Date('2026-08-03'),
    seller: MOCK_SELLERS[1] as any,
  },
  {
    id: 'car-4',
    sellerId: 'seller-2',
    title: '2021 BMW 320i',
    make: 'BMW',
    model: '320i',
    year: 2021,
    price: 22000000,
    currency: 'MWK',
    condition: 'CERTIFIED_PRE_OWNED',
    bodyType: 'SEDAN',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    mileage: 15000,
    color: 'Black',
    engineSize: '2.0L Turbo',
    features: ['Air Conditioning', 'Power Steering', 'Airbags', 'ABS', 'Leather Seats', 'Sunroof', 'Navigation', 'Premium Sound', 'Parking Sensors'],
    description: 'Certified pre-owned BMW 320i. Luxury and performance. Still under warranty.',
    images: [
      'https://images.unsplash.com/photo-1555215691-9a8b2a6b1e0d?w=800',
    ],
    status: 'ACTIVE',
    isFeatured: true,
    featuredUntil: new Date('2026-08-17'),
    views: 456,
    createdAt: new Date('2026-08-04'),
    updatedAt: new Date('2026-08-05'),
    seller: MOCK_SELLERS[1] as any,
  },
  {
    id: 'car-5',
    sellerId: 'seller-1',
    title: '2017 Nissan X-Trail',
    make: 'Nissan',
    model: 'X-Trail',
    year: 2017,
    price: 9500000,
    currency: 'MWK',
    condition: 'USED',
    bodyType: 'SUV',
    transmission: 'AUTOMATIC',
    fuelType: 'DIESEL',
    mileage: 62000,
    color: 'White',
    engineSize: '2.0L',
    features: ['Air Conditioning', 'Power Steering', 'Airbags', 'ABS', '4WD', 'Roof Rails', 'Bluetooth'],
    description: 'Reliable Nissan X-Trail diesel. Great for upcountry trips. 7-seater.',
    images: [
      'https://images.unsplash.com/photo-1533476408-66cd31e2a1a4?w=800',
    ],
    status: 'ACTIVE',
    isFeatured: false,
    featuredUntil: null,
    views: 134,
    createdAt: new Date('2026-08-05'),
    updatedAt: new Date('2026-08-05'),
    seller: MOCK_SELLERS[0] as any,
  },
  {
    id: 'car-6',
    sellerId: 'seller-2',
    title: '2019 Ford Ranger',
    make: 'Ford',
    model: 'Ranger',
    year: 2019,
    price: 18000000,
    currency: 'MWK',
    condition: 'USED',
    bodyType: 'PICKUP',
    transmission: 'MANUAL',
    fuelType: 'DIESEL',
    mileage: 40000,
    color: 'Silver',
    engineSize: '3.2L',
    features: ['Air Conditioning', 'Power Steering', 'Airbags', 'ABS', '4WD', 'Canopy', 'Tow Bar', 'Bluetooth'],
    description: 'Ford Ranger double cab. Workhorse for business and adventure. Canopy included.',
    images: [
      'https://images.unsplash.com/photo-1605581809338-4f3f9d12c1ed?w=800',
    ],
    status: 'ACTIVE',
    isFeatured: false,
    featuredUntil: null,
    views: 178,
    createdAt: new Date('2026-08-06'),
    updatedAt: new Date('2026-08-06'),
    seller: MOCK_SELLERS[1] as any,
  },
];
